# ===== SUPABASE CLOUD DATABASE =====
quarkus.datasource.db-kind=postgresql

# Pooler ke liye hamesha Project ID username mein honi chahiye
quarkus.datasource.username=postgres.vyfrvliwvmrrcyjndeqq
quarkus.datasource.password=Jariabbasrizvi786110!

# SAHI URL (Tokyo Region + Port 6543 + Parameter)
quarkus.datasource.jdbc.url=jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:5432/postgres?user=postgres.vyfrvliwvmrrcyjndeqq&password=Jariabbasrizvi786110!

# Hibernate strategy
quarkus.hibernate-orm.database.generation=update

quarkus.hibernate-orm.log.sql=false

quarkus.flyway.enabled=false

# ===== SERVER & OTHER SETTINGS =====
quarkus.http.port=8080
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger-ui
quarkus.rest-client.weather-api.url=https://api.openweathermap.org
weather.api.key=42dadee5d9c321165f42ccdde609db7a