# ===== DATABASE =====
quarkus.datasource.db-kind=mysql
quarkus.datasource.username=root
quarkus.datasource.password=
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/newswave_db?serverTimezone=UTC
quarkus.datasource.db-version=5.5.5
# ===== HIBERNATE =====
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true

# Enable CORS
quarkus.http.cors=true

# Allow frontend origin (dev)
quarkus.http.cors.origins=http://localhost:5173

# Methods
quarkus.http.cors.methods=GET,POST,PUT,PATCH,DELETE,OPTIONS

# Headers
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with

# Allow credentials (optional)
quarkus.http.cors.access-control-allow-credentials=true

# ===== SERVER =====
quarkus.http.port=8080

# ===== SWAGGER =====
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger-ui